BitcoinUnlimited/ElectrsCash

config_spec.toml, src/bin/electrscash.rs, src/cache.rs, src/config.rs, src/query.rs
This is #172 upstream. Pulling in here before upstream merge so it can make this release.
=> Add byte-size limit to transaction & block txids' caches

src/cache.rs
The match statement takes a lock, then a lock is attempted again when
putting an entry to the cache.
=> Fix recursive lock

src/app.rs, src/bin/electrscash.rs, src/bulk.rs, src/index.rs, src/mempool.rs, src/query.rs, src/rpc.rs, src/util.rs
This removes the expensive PeriodicUpdate call from application loop.
PeriodicUpdate would iterate through every subscription by every client
and re-calculate its status to look for differences.
The new code calculates which subscription need update and notifies each
RPC connection. If, and only if, a client is subscried will it
re-calculate its status.
=> Replace PerodicUpdate with notifications

src/cashaccount.rs, src/index.rs, src/mempool.rs, src/query.rs, src/rpc.rs
As is the spec for `get_history`.
Fixes #27
=> Identify transactions with unconfirmed parents

src/errors.rs, src/rpc.rs
Don't disconnect the client, return proper error instead. Fixes #25.
=> Return error on unknown method

examples/blockchain_scripthash_get_first_use.py, src/errors.rs, src/query.rs, src/rpc.rs
Implements new RPC call blockchain.scripthash.get_firstuse. This RPC
calls returns the hash of the first block scripthash was found in.
It returns a hash of all the transaction that have scripthash as output
in that block.
Note: Does not return transaction spending scripthash as input. Use
get_history for that.
Output from example script:
```
$ ./blockchain_scripthash_get_firstuse.py 
{'block_hash': '000000000000007f6c0e53f4560e15e1a805470144c00e1d81b78543e69c59c4', 'tx_hash': ['491aa3f7fd1f23882c3437898125259d2a0c044bea0f6aa659b8d7d6ab75632a']}
```
=> RPC call blockchain.scripthash.get_first_use

src/cache.rs, src/daemon.rs, src/query.rs, src/rpc.rs
Avoids call to bitcoind, and also puts the transaction into our cache.
Produces verbose output without help from bitcoind.
Tests added here: https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/2076
=> Use cache for blockchain.transaction.get 

src/bin/electrscash.rs, src/daemon.rs, src/query.rs, src/rpc.rs
* Use relay fee from `bitcoind` instead of hard coded value
* Don't warn on failing to notify peer
=> Upstream changes

config_spec.toml, src/bin/electrscash.rs, src/config.rs, src/errors.rs, src/lib.rs, src/query.rs, src/rpc.rs, src/timeout.rs
Add timeout checks to the most expensive RPC calls.
Timeout can be configured with a new option --rcp-timeout.
Closes #43
=> Add RPC timeout

config_spec.toml, src/bin/electrscash.rs, src/config.rs
Fixes issue where using RPC interface implies low memory preference.
=> Add config option to indicate low memory

Cargo.lock, Cargo.toml, config_spec.toml, examples/index.rs, src/bin/electrscash.rs, src/bulk.rs, src/cashaccount.rs, src/config.rs, src/index.rs, src/mempool.rs, src/query.rs
Don't index cashaccounts below cashaccount activation height. New
parameter --cashaccount-activation-height is added, which defaults to
activation on BCH.
Now that the piping is in place, a optimization to reuse allocated data
structure for parsing could also be added.
Closes #11
=> Start cashaccount indexing at activation height

src/query.rs, src/rpc/blockchain.rs, src/rpc/mod.rs, src/rpc/scripthash.rs
Adds:
- blockchain.address.get_balance
- blockchain.address.get_first_use
- blockchain.address.get_history
- blockchain.address.listunspent
Also fixes issue where listunspent would return wrong height for
unconfirmed transactions (with tests)
=> Partial blockchain.address.* implementations

src/daemon.rs
Both BU and BCHN have introduced in their API the possibility to call
getblockhash with _block height_ instead of _block hash_. Thus we don't need to call
getblockhash first.
Test plan:
./contrib/run_functional_tests.sh
=> Remove calls to 'getblockhash'

contrib/client.py
This adds a __main__ section to client.py so it can be used to test any
RPC calls.
Test plan:
```
$ python3 client.py "server.ping"
{'id': 0, 'jsonrpc': '2.0', 'result': None}
$ python3 client.py "blockchain.address.get_first_use"
"bitcoincash:qqfc3lxxylme0w87c5j2wdmsqln6e844xcmsdssvzy"
{'id': 0, 'jsonrpc': '2.0', 'result': {'block_hash':
'000000000000000002a04f56505ef459e1edd21fb3725524116fdaedf3a4d0ab',
'block_height': 597843, 'tx_hash':
'cef9c1485f166e92adf0b5d42e4ad202e4f5f9e2e7a072d0a6864c61c2cd6fa0'}}
$ python3 client.py "blockchain.address.get_scripthash"
"bitcoincash:qqfc3lxxylme0w87c5j2wdmsqln6e844xcmsdssvzy"
--server=bch.imaginary.cash
{'id': 0, 'jsonrpc': '2.0', 'result':
'273139c9327743dccc1030fc8d009e63e41e147c6b0449913d2dea5b71eef230'}
```
=> [contrib] Add generic cli for calling RPC methods

doc/rpc.md, src/query.rs, src/rpc/blockchain.rs, src/rpc/mod.rs
From upstream, extended with `block_height` as well.
=> rpc: Add call blockchain.transaction.get_confirmed_blockhash

src/bulk.rs, src/cache.rs, src/daemon.rs, src/index.rs, src/mempool.rs, src/metrics.rs, src/query.rs, src/rpc/mod.rs, src/rpc/rpcstats.rs
Don't re-export prometheus aliased datatypes.
The re-exports were inconsistent with prometheus. For instance,
prometheus::IntGauge was reexported as metric::Gauge, while
prometheus::Gauge as not exported and works with floats.
We don't plan on replacing prometheus, so to fix this, we just remove
this layer of abstraction.
=> Use prometheus imports

Cargo.lock, Cargo.toml, examples/compact.rs, examples/txid_collisions.rs, src/bin/electrscash.rs, src/store.rs
This adds 3 new prometheus metrics for observing rockdb memory usage.
=> metrics: Add rocksdb memory usage

config_spec.toml, src/bin/electrscash.rs, src/config.rs, src/doslimit.rs, src/errors.rs, src/lib.rs, src/rpc/blockchain.rs, src/rpc/mod.rs
This sets a limit on number of subscriptions per connection.
Test plan:
A RPC functional test has been added to Bitcoin Unlimited that covers this.
=> Add scripthash subscription limit

config_spec.toml, src/bin/electrscash.rs, src/config.rs, src/def.rs, src/doslimit.rs, src/rpc/blockchain.rs, src/rpc/mod.rs
Implements `blockchain.address.subscribe` and `blockchain.address.unsubscribe`.
New DoS limit has been added, which limits how many bytes we store of address data. Bytes is used instead of number of subscriptions, as addresses can vary in size, depending on prefix, length of encoded hash etc.
Test plan:
A functional test has been added to Bitcoin Unlimited that cover both the calls, as well as the new DoS limit.
=> rpc: Implement blockchain.address.(un)subscribe

Cargo.lock, Cargo.toml, config_spec.toml, contrib/websocket-client/cli.js, contrib/websocket-client/package.json, src/bin/electrscash.rs, src/config.rs, src/errors.rs, src/lib.rs, src/wstcp/LICENSE, src/wstcp/channel.rs, src/wstcp/frame.rs, src/wstcp/mod.rs, src/wstcp/opcode.rs, src/wstcp/server.rs, src/wstcp/util.rs
This adds experimental websocket support on ports 50003 for mainnet, 60003 for testnet.
It is currently implemented by proxying websocket connections to our RPC listening interface. It's implemented with code from the [wstcp](https://github.com/sile/wstcp/) project.
Ideally we should not be proxying, but rather responding to RPC requests directly on the websocket socket. This is the end goal, but requires more refactoring. This PR is first step towards good websocket support.
Test plan:
A websocket client has been added to `contrib/websocket-client`. 
```
websocket-client % node cli.js blockchain.address.get_balance bitcoincash:prnc2exht3zxlrqqcat690tc85cvfuypngh7szx6mk
{ confirmed: 217784148852, unconfirmed: 0 }
```
The PR is deployed on …
=> Add WebSocket support

config_spec.toml, src/bin/electrscash.rs, src/config.rs, src/doslimit.rs, src/rpc/mod.rs
This adds a limit to maximum number of simultaneous RPC connections. Any new connections after limit is reached will be immediately dropped.
Test plan:
New test added to `electrum_doslimit.py` to test this feature.
`./contrib/run_functional_tests.py`
=> rpc: Add RPC connection limit

config_spec.toml, src/bin/electrscash.rs, src/config.rs, src/doslimit.rs, src/metrics.rs, src/rpc/mod.rs
Mitigation against one actor using all connection slots.
The choice of using IP prefix was out of simplicity. This is probably not a great way to segregate connections.
Limitations: Because of the way websockets are implemented, this is effectively also a global limit for websocket connections.
Unit test added for this feature.
`cargo test`
`./contrib/run_functional_tests.py`
=> dos: Limit connections by IP prefix

src/app.rs, src/bin/electrscash.rs, src/cache.rs, src/mempool.rs, src/query/confirmed.rs, src/query/header.rs, src/query/mod.rs, src/query/primitives.rs, src/query/queryutil.rs, src/query/tx.rs, src/query/unconfirmed.rs, src/rpc/blockchain.rs, src/rpc/mod.rs, src/rpc/scripthash.rs
The query class has grown rather large. This is mainly moving
responsibility out of the class into smaller isolated classes.
The decoupling of responsibilities will make it easier to implement
(scripthash|blockchain).get_mempool as it allows for easier code reuse.
`cargo test && ./contrib/run_functional_tests.sh`
=> refactor: Split out responsibility of Query

src/cache.rs, src/daemon.rs, src/mempool.rs, src/query/mod.rs, src/query/tx.rs
There is no upper limit set on how many are batched, or how big they are. In
addition there is the unnecessary copying and logic support this.
By using the TxQuery class, all new mempool transactions are now put
into the transaction cache.
`cargo test && ./contrib/run_functional_tests.py`
=> Remove batch fetching of unconfirmed transactions 

Cargo.lock, Cargo.toml, src/def.rs, src/query/tx.rs, src/rpc/blockchain.rs
The electrum specification for verbose transaction is as follows:
> The result is a coin-specific dictionary – whatever the coin daemon returns when asked for a verbose form of the raw transaction.
In other words, it's undefined. In addition the performance of fetching the details from bitcoind is much worse that just creating it ourselves, as we can do so from the data in our transaction cache. This is also what ElectrsCash does.
This PR makes the output more like what we'd expect from any bitcoind, be it BU, BCHN or others. This is a breaking change.
The following changes have been made:
* `txout -> value` should not return satoshis, but as coins (`/ 100 000 000`). However, just changing the unit is dangerous, as we don't know what applications expect satoshis now. It's better to break …
=> Improve likeness with bitcoind getrawtransaction

config_spec.toml, src/daemon.rs, src/index.rs
The old semantics is to request 'index-batch-size' number of blocks in
one RPC request.
This sometimes causes a very large peak memory usage in bitcoind, as
index-batch-size number of potentially 32MB blocks need to be serialized as
JSON in one request. See issue #3.
The new semantics is add a sync buffer of size 'index-batch-size' to the
electrum server and continuously try to fill the buffer by fetching one
block at a time.
Full reindex of mainnet. Observe performance is not noticably impacted.
At around block height 360k, performance is at > 20 blocks/s.
```
$ tail -f debug.log | grep --line-buffered getblock | pv --line-mode -b --average-rate --rate > /dev/null
0.8k [18,7 /s] [20,7 /s]
(Requires with `debug=rpc` in `bitcoin.conf`)
```
=> Change semantics of index-batch-size

src/rpc/blockchain.rs
Adding a mutex around the subscription lists allows for remove of use of mutable self references.
`cargo test && ./contrib/run_functional_tests.sh`
=> Remove `mut self` in rpc blockchain

Cargo.lock, Cargo.toml, src/query/header.rs, src/query/mod.rs, src/query/queryutil.rs
Introduce generators to the code base.  Use generators to avoid loading more transactions than needed from bitcoind, as well as avoiding to have to load them all into memory at the same time.
=> Use generators with load_txns_by_prefix

Cargo.lock, Cargo.toml, src/query/confirmed.rs, src/query/queryutil.rs
Finding inputs/outputs for get history calls is CPU intensive. Use
parallel iter to speed up the query.
Simple benchmarking shows 3x speedup on my laptop for large histories,
such as the eatbch address.
Run the following with and without this change. This is the eatbch address which has about 13k transactions associated with it.
```
contrib % time python3 client.py --server localhost blockchain.address.get_history bitcoincash:pp8skudq3x5hzw8ew7vzsw8tn4k8wxsqsv0lt0mf3g > /dev/null
```
On my laptop, with this change
`0.07s user 0.03s system 5% cpu 1.721 total`
Without this change:
`0.07s user 0.02s system 1% cpu 4.885 total`
=> Use parallel iter for finding inputs/outputs

doc/rpc.md, src/query/tx.rs
This fixes an issue where it was not possible to get verbose transaction output for unconfirmed transactions.
In addition, the following changes are made to verbose output for unconfirmed transactions:
* `time` is None instead of 0
* `blockhash` is None instead of 0
* `height` is None instead of 0
* `confirmations` is None instead of 0. This is because `0` implies confirmed in a minority chain for some bitcoind implementations and unconfirmed in others.
Document that verbose output is consistent for ElectrsCash, regardless of bitcoind backend.
Functional test improved with unconfirmed transaction + testing of all these fields for both confirmed and unconfirmed.
=> bugfix: Unconfirmed transaction verbose output 

config_spec.toml, src/config.rs
Change defaults to listen for RPC and websocket connections on all
intefaces.
The project we forked from aimed to be a private server, so listening
only on localhost made sense. However, ElectrsCash is aimed to be a
public facing server.
The blocktxid cache is reduced and tx cache is incresed the same amount.
Observations shown in production show that tx cache is more used.
=> Update configuration defaults

src/rpc/mod.rs
Fixes issue found by @sickpig
```
2021-02-16 11:30:49 Electrum: TRACE - joining ThreadId(1954378)
2021-02-16 11:30:49 Electrum: TRACE - joining ThreadId(1954340)
2021-02-16 11:30:49 Electrum: INFO - RPC connections are closed
2021-02-16 11:30:49 Electrum: TRACE - RPC server is stopped
2021-02-16 11:30:49 Electrum: thread 'acceptor' panicked at 'send failed: "SendError(..)"', src/rpc/mod.rs:379:53
2021-02-16 11:30:49 Electrum: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-02-16 11:30:50 Electrum: TRACE - closing DB at "/home/sickpig/.bitcoin/electrscash/mainnet"
2021-02-16 11:30:50 Electrum: TRACE - done closing db
```
=> Handle send error at connect

src/index.rs, src/query/mod.rs, src/query/primitives.rs, src/query/queryutil.rs, src/query/unconfirmed.rs, src/rpc/scripthash.rs
This removes our own OutPoint type alias, switching all use to the
OutPoint struct in the bitcoincash crate.
`cargo test && ./contrib/functional_tests.sh`
=> Use 'OutPoint' from the bitcoincash crate

doc/rpc.md, src/daemon.rs, src/errors.rs, src/mempool.rs, src/query/confirmed.rs, src/query/header.rs, src/query/mod.rs, src/query/queryutil.rs, src/query/tx.rs, src/query/unconfirmed.rs, src/rpc/blockchain.rs, src/rpc/mod.rs, src/rpc/parseutil.rs
Add RPC call `blockchain.utxo.get` with the following interface
```
{
"state": "spent" || "unspent",
"height":  height # height of the tx creating the utxo is confirmed in (0 for mempool, -1 if spender has unconfirmed parent)
"value": value # value of utxo in satoshis
"scripthash": scripthash # scriphash of the output scriptPubKey
"spent": {
"tx_hash": txid, # id of the tx spending the utxo
"tx_pos": pos, # input index in the spending transaction
"height": height # height of the block spender is confirmed in (0 for mempool, -1 if spender has unconfirmed parent)
},
}
```
=> Add `blockchain.utxo.get`
