BitcoinUnlimited/ElectrsCash

Cargo.toml
RELEASE-NOTES.md
contrib/determinism-build-check.py
contrib/elfcompare.py

Reverts "Build with LTO" (83bbfaa) and add tools to test deterministic build.
Tools are based on work by @gandrewstone

Fix deterministic build

---

Cargo.lock
Cargo.toml
contrib/cashaccount.py
doc/schema.md
src/cashaccount.rs
src/index.rs
src/lib.rs
src/query.rs
src/rpc.rs

Adds indexing of cash accounts and new RPC call, `cashaccount.query.name`

Add CashAccount indexing and querying

---

Cargo.lock
Cargo.toml
RELEASE-NOTES.md
contrib/addr.py
contrib/cashaccount.py
contrib/client.py
contrib/daemon.py
contrib/mempool.py
contrib/tx_fee.py
contrib/xpub.py
doc/usage.md
src/query.rs

This pulls in v0.7.1 changes from upstream

Pull in v0.7.1 changes

---

contrib/bench/README.md
contrib/bench/package.json
contrib/bench/server-compare.js

Benchmarking script for comparing server performance. See ascii-cast:
[![asciicast](https://asciinema.org/a/262851.svg)](https://asciinema.org/a/262851)

[bench] Script to compare server performance

---

Cargo.toml
RELEASE-NOTES.md

Bump version, update readme

---

src/rpc.rs

Fixes #24
This is missing the hosts key, but if we can agree on https://github.com/dagurval/electrum-cash-protocol/pull/1, that's not an issue.

Implement server.features

---

src/rpc.rs

Thread attempts a lock on handles, while handles is locked in a join.
Copy handle ids rather than holding the lock.

Fix deadlock in rpc connections

---

src/rpc.rs

Returns error code for invalid param, rather than internal error.
Returns two last errors in error chain for better description.

Improve error on invalid argument

---

src/query.rs
src/rpc.rs

Block lookup improvements

---

src/rpc.rs

Bump max protocol version to 1.4.1

---

src/bin/electrscash.rs

First iteration if the main loop can include all blocks after the start
of the intial index.
It can take a while to generate notifications for all the transaction in
these blocks and there are no clients connected anyway. So skip it.

Don't send notification at startup

---

src/bin/electrscash.rs
src/bulk.rs
src/def.rs
src/fake.rs
src/index.rs
src/lib.rs
src/rpc.rs
src/store.rs

Add DB version and reindex on incompatible version

---

src/config.rs

Load cookie from correct path in testnet & regtest mode

Fix cookie path

---

config_spec.toml
src/bin/electrscash.rs
src/config.rs
src/rpc.rs

And make the size configurable. Fixes issue with dropped client
notifications.

Bump rpc connection buffer size

---

src/rpc/mod.rs

If a client drops the connection and we're unable to send to them,
that's not our fault (broken pipe). Reduce log level from error to
debug.
This also removes a DoS vector where a client can fill our log with
error messages, waisting disk space.

Reduce log level on client errors

---

Cargo.lock
Cargo.toml
RELEASE-NOTES.md

Update release notes and package version

Prepare for 1.1.1 release

---

src/rpc/mod.rs
src/rpc/server.rs

Move remaining `server.*` methods from `mod.rs` to `server.rs`.
Also includes a commit to add a stub for `server.add_peer`

Move server.* methods

---

src/rpc/mod.rs
src/rpc/parseutil.rs

Move remaining helper functions to parserutil. 
Prerequisite to #49

Move remaining parameter parser functions

---

src/bin/electrscash.rs
src/rpc/blockchain.rs
src/rpc/mod.rs

Move blockchain.* functions from mod.rs -> blockchain.rs

Move blockchain.* functions

---

src/cashaccount.rs
src/index.rs
src/lib.rs
src/query.rs
src/rpc/blockchain.rs
src/rpc/mod.rs
src/rpc/parseutil.rs
src/scripthash.rs
src/util.rs

Removes hackish use of the Sha256dHash type

Always use FullHash for scripthashes

---

src/def.rs
src/rpc/blockchain.rs
src/rpc/mod.rs
src/rpc/parseutil.rs

Test added to qa framework
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/2190

Implement blockchain.scripthash.unsubscribe

---

src/rpc/blockchain.rs
src/rpc/mod.rs
src/rpc/rpcstats.rs

Don't duplicate metric names

---

src/query.rs

More accurate timeout by checking for timeout between loading tx output
transactions.
Test plan:
./contrib/run_functional_tests.sh

Add new timeout check

---

src/rpc/scripthash.rs

This makes it consistent with other RPC calls.
Test plan:
- Added test here: https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/2239
- `./contrib/run_functional_tests.sh`

Change 'block_height' to 'height' in get_first_use

---

src/daemon.rs

This reverts commit 5b06b668f415a42ea129cf3611dfe27de7e34591.
Fixes #92
Test plan:
```
./contrib/run_functional_tests.sh
```

Revert "Remove calls to 'getblockhash'"

---

contrib/client.py

Supports boolean and numbers. For example, now you can use the verbose
argument of transaction.get
`client.py blockchain.transaction.get txid true`

[contrib] Support more data types in client.py

---

src/rpc/blockchain.rs

Don't store scripthash subscriptions json encoded. Use FullHash to save
on memory and CPU.
Test plan:
`./contrib/run_functional_tests.py`

performance: Store statushashes as FullHash

---

src/rpc/blockchain.rs

Test plan:
* [  ] Create a functional test
* `./contrib/run_functional_tests.sh`

Make height optional in transaction.get_merkle

---

src/query/mod.rs
src/rpc/blockchain.rs
src/rpc/mod.rs
src/rpc/scripthash.rs

This implements blockchain.scripthash.get_mempool and
blockchain.address.get_mempool.
Add functional test

Implement blockchain.*.get_mempool

---

src/doslimit.rs

Adds the following new prometheus counters:
- `electrscash_rpc_connections`: Number of current connections.
- `electrscash_rpc_connections_total`: Connections since server was started.
- `electrscash_rpc_connections_rejected_global`: Connections rejected due to global limits
- `electrscash_rpc_connections_rejected_prefix`: Connections rejected due to IP prefix
Run `./contrib/client.py --server localhost server.ping`. Observe that total counter increases. Add `time.sleep(100)` to client. Observe that `current connection counter is correct.

Add connection stats to prometheus stats

---

Cargo.toml
src/bin/electrscash.rs
src/cashaccount.rs
src/index.rs
src/mempool.rs
src/query/mod.rs
src/query/tx.rs
src/util.rs

Adds missing field 'addresses'.
Added to functional test

Add addressses to verbose tx output

---

Cargo.lock
Cargo.toml
src/bulk.rs
src/config.rs
src/daemon.rs
src/query/tx.rs

Add testnet4 and scalenet support

---

examples/compact.rs
examples/txid_collisions.rs
src/app.rs
src/bin/electrscash.rs
src/bulk.rs
src/config.rs
src/daemon.rs
src/index.rs
src/metrics.rs
src/query/mod.rs
src/rpc/blockchain.rs
src/rpc/mod.rs
src/rpc/rpcstats.rs
src/rpc/scripthash.rs
src/scripthash.rs
src/store.rs

Changes to make clippy happy again.

Clippy updates for rust 1.51

---

src/app.rs
src/bin/electrscash.rs
src/bulk.rs
src/cache.rs
src/daemon.rs
src/doslimit.rs
src/index.rs
src/metrics.rs
src/query/confirmed.rs
src/query/header.rs
src/query/mod.rs
src/query/queryutil.rs
src/query/tx.rs
src/query/unconfirmed.rs
src/rpc/blockchain.rs
src/rpc/mod.rs
src/rpc/scripthash.rs
src/rpc/server.rs
src/util.rs
src/wstcp/channel.rs
src/wstcp/frame.rs
src/wstcp/server.rs

Update code to pass linters included with latest stable rust.

chore: Run `cargo clippy`

---

Cargo.toml
RELEASE-NOTES.md

Bump version and add release notes.

Version bump to v3.1
